build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:latest
  amd64: ghcr.io/home-assistant/amd64-base:latest
  armv7: ghcr.io/home-assistant/armv7-base:latest
args:
  GO_VERSION: "1.21"
labels:
  io.hass.version: "1.0.0"
  io.hass.type: "addon"
  io.hass.arch: "aarch64|amd64|armv7"
